{
    "context": {
        "sources": [{
            "srcset": "https://source.unsplash.com/random/1600x900",
            "media": "(min-width: 64em)"
        },{
            "srcset": "https://source.unsplash.com/random/1024x768",
            "media": "(min-width: 45em)"
        }]
    }
}
